### PR TITLE
pyatspi: print app name for focus selected events

### PR DESCRIPTION
**Pull request by thisMagpie**
Ref: https://github.com/infapi00/at-spi2-examples/pull/2

### CODE REVIEW

**Comment by infapi00** [comment]
With this change, it goes from printing the accessible object name and role, to only the application name. I think that all info are useful. C counterpart prints the following information for each accessible object:
(application name, accessible object name, role name, state set).

For example:
(gedit, File, menu, [enabled,selectable,selected,sensitive,showing,visible])

**Comment by thisMagpie** [comment]
Sure, I'll amend it to have all the information.

**Comment by thisMagpie** [comment]
OK @infapi00 I think this is what you meant and it looks a lot more useful on the terminal.

**Comment by thisMagpie** [comment]
I just added the detail because I noticed it was missing and I think it is useful information too.

**Comment by infapi00** [comment]
Looks good, and we can leave the stateset for the future. Just one question. Any reason for having three commits instead of just one?

**Comment by thisMagpie** [comment]
Nah, I was just being lazy. I can make into a single commit if that's preferable?

**Comment by infapi00** [comment]
> Nah, I was just being lazy. I can make into a single commit if that's preferable?

Yes, please

**Comment by thisMagpie** [comment]
I created a new branch for the commit at https://github.com/infapi00/at-spi2-examples/pull/6

**Pull request closed without merging**
