### PR TITLE
Print application name and event type for emitted events

### PR DESCRIPTION
**Pull request by thisMagpie**
Relevant events:
window
object:state-changed:selected
object:state-changed:focused

### CODE REVIEW

**Comment by thisMagpie** [comment]
@infapi00 I'm not sure whether you saw this or not.

I have another one for property-change:table events but I just need to find a suitable application to test them with (suggestions welcome)

**Comment by infapi00** [comment]
The name of print_accessible_name is somewhat misleading. As far as I see, the main objective of that example is react to a property-change (in this case accessible-name). And related to that, if we add a example to react to property-change:accessible-name, I don't see the need of adding a example to just react to property-change:table. The idea of this examples are having small programs to use as examples, not having programs testing all the at-spi API. That is the purpose of unit tests. If we have a test showing how to follow property-change:accessible-name, what extra value provides an example following property-change:table? 

And finally, this pull request includes a commit that is a merge from master, called "Update fork with Alejandro's master changes". As the idea of this pull request is merge with master, I don't think that is a good idea asking to merge a commit that is already there. In any case, note that I'm not really used to github flow, so I could be wrong.

**Comment by thisMagpie** [comment]
Hi @infapi00,

Thanks for the merge and comments. 

I am happy to change the name for the accessible-name listener and I agree, I was just a bit conscious of how long the names are getting! Any suggestions for how we can keep the script names consistent and yet concise?

I am not sure how useful a table* property events listener would be for people in general, but for me I feel it would be very useful. Accerciser crashes a lot and I want to test these events in the wrapper with SwingSet table demo which makes these scripts a more time efficient way of narrowing on the events for me, I expect to produce a few more because of this.

At the moment my table property-change tests are not producing any table property change events with the table viewer in SwingSet with accerciser, so I am keen to determine whether this is a problem in the wrapper or whether this is normal by comparing the result to a non java application's results for table property listeners but I have yet to find an application which I can use to focus on testing just these events with (i.e. I have yet to see these events be emitted by anything at all)

The merge you're wondering about was me updating my master with your changes (i.e. your work outside pyatspi) to bring it up to date. I guess it must show up on yours because I had an open pull request at the time? I'm not sure how to resolve that to be honest but I'll have a look.

**Comment by thisMagpie** [comment]
On further thought: How about I make that into a print_property_change.py script? That way the name will make sense, it will include all the properties (including the table properties) as the print window script does with window events?

**Comment by thisMagpie** [comment]
I'll close this one and do individual requests so I can take out the ones you didn't like. Here's the first https://github.com/infapi00/at-spi2-examples/pull/4

**Pull request closed without merging**
